(n,minFeatureInd,maxFeatureInd,numTotal,minfeature,maxfeature) = getStats("data/agaricus/agaricus")
println("Number of datapoints = $n")
println("minFeatureInd   = $minFeatureInd")
println("maxFeatureInd   = $maxFeatureInd")
println("number of features   = $(maxFeatureInd-minFeatureInd+1)")
println("numTotal   = $(numTotal)")
println("sparsity   = $(numTotal/(n*(maxFeatureInd-minFeatureInd+1)))")
println("minfeature   = $minfeature")
println("maxfeature   = $maxfeature")

(features, labels)  = readData("data/agaricus/agaricus", (n,maxFeatureInd-minFeatureInd+1), minFeatureInd)