language: julia
julia:
 - release
 - nightly
services:
 - redis-server
script:
 - julia -e 'Pkg.add("StatsBase"); Pkg.clone(pwd()); Pkg.test("EGR", coverage = true)'
after_success:
 - julia -e 'cd(Pkg.dir("EGR")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'