language: julia
julia:
  - release
  - nightly
script:
- julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("EGR")'
- julia --code-coverage test/runtests.jl
after_success:
- julia -e 'cd(Pkg.dir("EGR")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'